// @ts-check
"use strict";
/* ============================================================================
   Walkable Isometric Presentation  ·  vanilla JS + HTML5 Canvas  ·  zero deps
   ----------------------------------------------------------------------------
   A participant walks an isometric room with WASD / arrow keys and presses E
   (or Space to auto-walk) at each kiosk to view one of your slides.

   WHERE SLIDES COME FROM (resolved at startup, first match wins):
     1. window.SLIDES_MANIFEST  — from slides.js (generated by build_slides.py).
     2. runtime image-probe     — slides/1.<ext>, slides/2.<ext>, ... if present.
     3. PLACEHOLDER_SLIDES       — the built-in demo cards below.
   The room re-lays-itself-out from however many slides are found.

   A slide can be:  { type:"image", src, title }   (png/jpg/webp/svg/gif…)
                    { type:"pdf",   src, title }    (scrollable document)
                    { type:"html",  src, title }    (scrollable document, file)
                    { type:"html",  html, title }   (scrollable, inline markup)
                    { type:"embed", src, title }    (16:9 iframe — YouTube/Vimeo/any URL)

   ARCHITECTURE:  1 CONFIG  2 STATE  3 AUDIO  3b NET  4 SLIDE LOADING  5 ROOM LAYOUT
                  6 INIT  7 INPUT  8 UPDATE  9 RENDER  10 SLIDE MODAL  11 HELPERS
   No build step for the game itself. Edit, save, refresh.
   See CLAUDE.md for an architecture tour + "how do I…" extension recipes.
   ========================================================================== */

/* ----------------------------------------------------------------------------
   1. CONFIG  — edit me
   -------------------------------------------------------------------------- */

const TALK_TITLE = "Your Presentation";

/** Public URL the start-screen "scan to open on your phone" QR encodes.
 *  ""  → auto-use the address the page is actually served from: your LAN IP when you
 *        serve on the LAN (so a phone scan opens THIS build — best for testing), or the
 *        Render URL when running on Render. Hidden on file:// and localhost (a phone
 *        can't reach those). This is the default you usually want.
 *  Or hard-pin it to always point somewhere regardless of how the page is opened, e.g.
 *  "https://cgsa2026-audio-presentation.onrender.com/" to always send phones to Render. */
const JOIN_URL = "";

const TILE_W = 96;          // isometric tile width  (px)
const TILE_H = 48;          // isometric tile height (px)  — 2:1 is classic iso
const PLAYER_SPEED = 5.0;   // tiles per second
const INTERACT_RANGE = 1.8; // how close (tiles) you must be to open a slide
const OBSTACLE_RADIUS = 0.8;// kiosks gently block you within this radius (tiles)
const KIOSK_SPACING = 3.4;  // desired tile gap between kiosks on the ring

/** Kiosk accent colours, assigned round-robin as the room is generated. */
const KIOSK_PALETTE = ["#ff6b6b", "#feca57", "#48dbfb", "#5f27cd", "#1dd1a1",
                       "#ff9ff3", "#54a0ff", "#00d2d3", "#ff7f50", "#a29bfe"];

/**
 * @typedef {{ type?:string, src?:string, html?:string, title:string }} Slide
 */
/** Used only when no manifest and no probed images are found. @type {Slide[]} */
const PLACEHOLDER_SLIDES = [
  { title: "Welcome",      html: phCard(1, "Welcome", "This is a walkable poster. Move with WASD/arrows, press E (or Space to auto-walk) at a kiosk to view its slide.") },
  { title: "The Problem",  html: phCard(2, "The Problem", "Replace this with the problem your talk addresses — or add real slides (see README).") },
  { title: "Our Approach", html: phCard(3, "Our Approach", "Replace this with your method or key idea.") },
  { title: "Results",      html: phCard(4, "Results", "Replace this with your findings.") },
  { title: "Q&A · Thanks", html: phCard(5, "Q&A · Thanks", "Thanks for visiting! Add contact details or a QR code here.") },
];

/* --- Avatar: four unnamed sheetghost colourways (no white). Random at startup;
       press C in-game / pick on the start screen to change. -------------------
   @typedef {{ sheet:string, shade:string, eye:string, pattern?:"dots" }} SheetTheme */
/** @type {SheetTheme[]} */
const SHEET_THEMES = [
  { sheet: "#ff2b2b", shade: "#c21a1a", eye: "#2121de" }, // red
  { sheet: "#ffb8ff", shade: "#e58ee5", eye: "#2121de" }, // pink
  { sheet: "#19dede", shade: "#0e9c9c", eye: "#2121de" }, // cyan
  { sheet: "#ffb852", shade: "#d98e2a", eye: "#2121de" }, // orange
];

/* --- Multiplayer (optional; active only when the page is served by serve.py) --- */
const NET_SYNC_MS = 120;   // ms between position exchanges with the relay
const NET_LERP = 0.18;     // remote-ghost position smoothing per frame (0..1)
const MSG_MAX = 100;       // max characters in a ghost's speech-bubble message (serve.py caps too)

/* --- Audio: sine-tone sound design ----------------------------------------- */
const MASTER_VOLUME = 0.85;
const ROOT_FREQ = 261.63;        // C4 — base pitch
const SCALE = [0, 2, 4, 7, 9];   // major pentatonic (semitone offsets)

/* ----------------------------------------------------------------------------
   2. STATE
   -------------------------------------------------------------------------- */

/** @type {HTMLCanvasElement} */ // @ts-ignore  (guaranteed present in index.html)
const canvas = document.getElementById("game");
const ctx = /** @type {CanvasRenderingContext2D} */ (canvas.getContext("2d"));

let W = 0, H = 0, dpr = 1;          // CSS pixels + device-pixel-ratio
let originX = 0, originY = 0;        // camera offset (recomputed each frame)
let tnow = 0;                        // seconds, for animations
let last = 0;                        // last frame timestamp

/** @type {"intro"|"walking"|"slide"} */
let state = "intro";

let GRID = 14;                       // room size (recomputed by buildRoom)
/** @type {Slide[]} */ let SLIDES = [];
/**
 * @typedef {{ tx:number, ty:number, title:string, color:string, slide:number, visited:boolean }} Exhibit
 */
/** @type {Exhibit[]} */ let EXHIBITS = [];

let currentSlide = 0;
let activeIndex = -1;                // exhibit currently in interaction range
let prevActive = -1;                 // for "stepped into range" sound
let currentTarget = -1;              // last slide reached/viewed (for Space → next)
let sheetIndex = 0;                  // current SHEET_THEMES index

const player = { x: 6.5, y: 6.5, fx: 0, fy: 1, moving: false };
const keys = { up: false, down: false, left: false, right: false };
// Auto-walk: Space → next kiosk, or a tap/click → a kiosk (goal>=0, opens on
// arrival) or a free floor point (goal<0, walk to auto.tx/ty and stop).
const auto = { active: false, goal: -1, tx: 0, ty: 0, lastDist: Infinity, stuck: 0 };

/** Highlighted "walkway" tiles connecting the kiosks. @type {Set<string>} */
const pathTiles = new Set();

let toastText = "", toastUntil = 0;  // transient on-screen message

// DOM references (filled in init)
let introEl, slideEl, slideCardEl, slideTitleEl, slideCounterEl, slideStageEl,
    hudHintEl, hudProgressEl, startBtn;
let lastVisited = -1, lastHint = "";
let mpNameWrap = null, mpNameEl = null, mpStatusEl = null; // multiplayer DOM (optional)
let msgComposerEl = null, msgInputEl = null, chatBtnEl = null; // speech-bubble composer (F key / 💬 on touch)

/** One remote visitor. x,y are the *rendered* position; tx,ty the latest reported
 *  target we ease toward. @typedef {{x:number,y:number,tx?:number,ty?:number,fx:number,fy:number,name:string,sheet:number,msg?:string}} Peer */
/** Multiplayer state — stays inert unless serve.py's relay answers (see §3b NET). */
const net = {
  on: false, base: "", id: "", name: "", room: "main",
  msg: "", composing: false,        // this ghost's speech-bubble text + whether the composer is open
  /** @type {Map<string, Peer>} */ peers: new Map(),
  inflight: false, lastSent: 0, fails: 0,
};

/* ----------------------------------------------------------------------------
   3. AUDIO ENGINE  — sine-tone SFX (+ generative-music hook)
   ----------------------------------------------------------------------------
   Built from one primitive, audio.tone(), plus noteFreq(degree) over SCALE.
   Each kiosk plays its own note, so interactions are already musical.

   >>> GENERATIVE MUSIC (future) <<<  Run a lookahead scheduler that queues
   audio.tone(noteFreq(pick), { delay, gain:0.05, dur }) ahead of
   audio.ctx.currentTime; start it from startGame(); keep its gain low so SFX
   sit on top.
   -------------------------------------------------------------------------- */

/** @param {number} degree @returns {number} frequency in Hz */
function noteFreq(degree) {
  const n = SCALE.length;
  const oct = Math.floor(degree / n);
  const semi = SCALE[((degree % n) + n) % n] + 12 * oct;
  return ROOT_FREQ * Math.pow(2, semi / 12);
}

const audio = {
  /** @type {AudioContext|null} */ ctx: null,
  /** @type {GainNode|null} */ master: null,
  muted: false,
  ensure() {
    if (this.ctx) return;
    const AC = window.AudioContext || /** @type {any} */ (window).webkitAudioContext;
    if (!AC) return;
    this.ctx = new AC();
    this.master = this.ctx.createGain();
    this.master.gain.value = this.muted ? 0 : MASTER_VOLUME;
    this.master.connect(this.ctx.destination);
  },
  resume() { if (this.ctx && this.ctx.state === "suspended") this.ctx.resume(); },
  /** @param {boolean} m */
  setMuted(m) {
    this.muted = m;
    if (this.ctx && this.master) this.master.gain.setTargetAtTime(m ? 0 : MASTER_VOLUME, this.ctx.currentTime, 0.02);
  },
  /** @param {number} freq @param {{delay?:number,dur?:number,gain?:number,attack?:number,type?:OscillatorType}} [o] */
  tone(freq, o) {
    if (!this.ctx || !this.master || this.muted) return;
    const t = this.ctx.currentTime + (o?.delay ?? 0);
    const dur = o?.dur ?? 0.15, peak = o?.gain ?? 0.22;
    const osc = this.ctx.createOscillator(), g = this.ctx.createGain();
    osc.type = o?.type ?? "sine";
    osc.frequency.value = freq;
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(peak, t + (o?.attack ?? 0.01));
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    osc.connect(g); g.connect(this.master);
    osc.start(t); osc.stop(t + dur + 0.03);
  },
};

const sfx = {
  interact(degree) { audio.tone(noteFreq(degree), { gain: 0.26, dur: 0.18 }); audio.tone(noteFreq(degree + 2), { delay: 0.085, gain: 0.20, dur: 0.16 }); },
  enter(degree) { audio.tone(noteFreq(degree), { gain: 0.09, dur: 0.09 }); },
  close() { audio.tone(noteFreq(1), { gain: 0.11, dur: 0.12 }); audio.tone(noteFreq(0), { delay: 0.07, gain: 0.09, dur: 0.13 }); },
  nav() { audio.tone(noteFreq(2), { gain: 0.07, dur: 0.05 }); },
  sheet() { audio.tone(noteFreq(4), { gain: 0.14, dur: 0.10 }); },
};

/* ----------------------------------------------------------------------------
   3b. NET  — optional multiplayer (served by serve.py). Degrades silently to solo.
   ----------------------------------------------------------------------------
   When serve.py is hosting the page, /net/info answers and we start trading ghost
   positions: POST our {x,y,…} every NET_SYNC_MS and draw everyone else's ghost
   (interpolated). Opened from file:// or a plain static server the probe just
   fails and this stays exactly the single-player game it has always been.
   -------------------------------------------------------------------------- */

function netRandomName() { return "Ghost-" + (1000 + Math.floor(Math.random() * 9000)); }

/** Probe for the relay; wire up identity + the (otherwise hidden) name field. */
function netInit() {
  net.name = netRandomName();
  if (mpNameEl) mpNameEl.value = net.name;
  if (!/^https?:$/.test(location.protocol)) return;   // file:// has no relay → stay solo
  net.base = location.origin;
  net.id = (window.crypto && crypto.randomUUID)
    ? crypto.randomUUID() : "g" + Math.random().toString(36).slice(2) + Date.now();
  try { net.room = new URLSearchParams(location.search).get("room") || "main"; } catch (e) { /* ignore */ }
  fetch(net.base + "/net/info", { cache: "no-store" })
    .then(r => r.ok ? r.json() : null)
    .then(info => { if (info && info.multiplayer) { net.on = true; if (mpNameWrap) mpNameWrap.classList.remove("hidden"); } })
    .catch(() => { /* no relay here — single-player, no noise */ });
}

/** Frame hook: pace the position exchange. @param {number} ts */
function netTick(ts) { if (net.on && !net.inflight && ts - net.lastSent >= NET_SYNC_MS) netSync(); }

/** One round-trip: send my ghost, receive everyone else's. */
function netSync() {
  net.inflight = true; net.lastSent = performance.now();
  net.name = (mpNameEl && mpNameEl.value.trim()) || net.name;
  const body = JSON.stringify({
    id: net.id, room: net.room, name: net.name, sheet: sheetIndex, msg: net.msg,
    x: +player.x.toFixed(3), y: +player.y.toFixed(3), fx: +player.fx.toFixed(3), fy: +player.fy.toFixed(3),
  });
  fetch(net.base + "/net/sync", { method: "POST", cache: "no-store", headers: { "Content-Type": "application/json" }, body })
    .then(r => r.ok ? r.json() : Promise.reject(r.status))
    .then(data => {
      net.fails = 0;
      const seen = new Set();
      for (const p of (data.players || [])) {
        seen.add(p.id);
        let peer = net.peers.get(p.id);
        if (!peer) { peer = { x: p.x, y: p.y, fx: p.fx, fy: p.fy, name: p.name, sheet: p.sheet }; net.peers.set(p.id, peer); }
        peer.tx = p.x; peer.ty = p.y; peer.fx = p.fx; peer.fy = p.fy; peer.name = p.name; peer.sheet = p.sheet; peer.msg = p.msg || "";
      }
      for (const id of [...net.peers.keys()]) if (!seen.has(id)) net.peers.delete(id);
    })
    .catch(() => { if (++net.fails > 25) { net.on = false; net.peers.clear(); } }) // relay vanished → solo
    .finally(() => { net.inflight = false; });
}

/** Ease each remote ghost toward its latest reported position (smooths ~8 Hz updates). */
function lerpPeers() {
  for (const peer of net.peers.values()) {
    if (peer.tx === undefined || peer.ty === undefined) continue;
    peer.x += (peer.tx - peer.x) * NET_LERP;
    peer.y += (peer.ty - peer.y) * NET_LERP;
  }
}

/** Draw one remote visitor's ghost + name tag. @param {Peer} peer */
function drawPeer(peer) {
  const c = toScreen(peer.x, peer.y);
  const n = SHEET_THEMES.length;
  const theme = SHEET_THEMES[((peer.sheet % n) + n) % n] || SHEET_THEMES[0];
  let sdx = peer.fx - peer.fy, sdy = (peer.fx + peer.fy) * 0.5;
  const sm = Math.hypot(sdx, sdy) || 1; sdx /= sm; sdy /= sm;
  const hover = Math.sin(tnow * 2.2 + (peer.x + peer.y)) * 2.0;
  shadow(c.x, c.y, 14);
  ctx.globalAlpha = 0.9;
  paintGhost(ctx, c.x, c.y - 8 + hover, 1, theme, sdx, sdy);
  ctx.globalAlpha = 1;
  if (peer.msg) speechBubble(peer.msg, c.x, c.y - 44 + hover);     // a posted message takes the place of the name tag
  else label(peer.name || "Ghost", c.x, c.y - 48 + hover, 12, "#cfe1ff");
}

/* ----------------------------------------------------------------------------
   4. SLIDE LOADING  — manifest -> image-probe -> placeholders
   -------------------------------------------------------------------------- */

/** Resolve the slide list. @returns {Promise<Slide[]>} */
async function loadSlides() {
  const manifest = /** @type {any} */ (window).SLIDES_MANIFEST;
  if (Array.isArray(manifest) && manifest.length) return manifest.map(normalizeSlide);

  const probed = await probeImageSlides();
  if (probed.length) return probed;

  return PLACEHOLDER_SLIDES.map(normalizeSlide);
}

/** Fill in `type` (and a title) for a manifest/placeholder entry. @param {any} s @returns {Slide} */
function normalizeSlide(s, i) {
  const type = s.type || (s.html ? "html" : s.src ? guessType(s.src) : "html");
  return { type, src: s.src, html: s.html, title: s.title || `Slide ${(i ?? 0) + 1}` };
}

/** Pre-fetch every html slide's document (http(s) only) and keep it on the slide
 *  as `s.html`, so opening a kiosk renders instantly from `srcdoc` instead of a
 *  per-open network round-trip (= the white frame on slow links). An injected
 *  <base> keeps the doc's relative asset paths (figures) working from srcdoc,
 *  whose base URL is the page's, not slides/; those assets are fetched once here
 *  too, warming the HTTP cache. file:// can't fetch() — skipped there, where
 *  local loads are instant anyway. Any failure leaves the iframe-src fallback.
 *  @param {Slide[]} slides */
function preloadSlideDocs(slides) {
  if (!/^https?:$/.test(location.protocol)) return;
  for (const s of slides) {
    if (s.type !== "html" || !s.src || s.html) continue;
    const dir = s.src.replace(/[^/]*$/, "");                        // e.g. "slides/"
    fetch(s.src).then(r => r.ok ? r.text() : Promise.reject(r.status)).then(text => {
      s.html = text.replace(/<head([^>]*)>/i, `<head$1><base href="${dir}">`);
      for (const m of text.matchAll(/<img[^>]+src="([^"]+)"/gi)) {  // warm the figures
        if (!/^(?:[a-z]+:|\/)/i.test(m[1])) fetch(dir + m[1]).catch(() => {});
      }
    }).catch(() => { /* keep s.src; the iframe loads it the old way */ });
  }
}

/** Probe slides/1.<ext>, slides/2.<ext>, … until a gap. Works over file://.
 *  @returns {Promise<Slide[]>} */
async function probeImageSlides() {
  const exts = ["png", "jpg", "jpeg", "webp", "gif", "svg", "avif"];
  const out = [];
  for (let n = 1; n <= 200; n++) {
    let found = null;
    for (const e of exts) {
      const src = `slides/${n}.${e}`;
      if (await imageExists(src)) { found = src; break; }
    }
    if (!found) break;
    out.push({ type: "image", src: found, title: `Slide ${n}` });
  }
  return out;
}

/** @param {string} src @returns {Promise<boolean>} */
function imageExists(src) {
  return new Promise(res => { const im = new Image(); im.onload = () => res(true); im.onerror = () => res(false); im.src = src; });
}

/** @param {string} src @returns {string} slide type from a file extension (or video URL) */
function guessType(src) {
  if (/^https?:\/\//i.test(src) &&
      /(?:youtube\.com|youtu\.be|youtube-nocookie\.com|vimeo\.com)/i.test(src)) return "embed";
  const ext = (src.split(/[?#]/)[0].split(".").pop() || "").toLowerCase();
  if (ext === "pdf") return "pdf";
  if (ext === "html" || ext === "htm") return "html";
  return "image";
}

/** Normalise a video/watch URL to its iframe-embeddable form (YouTube → privacy-
 *  enhanced nocookie embed, Vimeo → player); anything else is returned unchanged,
 *  so an already-embeddable page or a generic site just embeds as-is.
 *  @param {string} url @returns {string} */
function toEmbedUrl(url) {
  const u = String(url).trim();
  /** @type {RegExpMatchArray|null} */ let m;
  if ((m = u.match(/(?:youtube\.com\/(?:watch\?(?:.*&)?v=|embed\/|shorts\/|live\/)|youtu\.be\/)([\w-]{6,})/i))) {
    const t = (u.match(/[?&](?:t|start)=(\d+)/) || [])[1];
    return `https://www.youtube-nocookie.com/embed/${m[1]}?rel=0${t ? "&start=" + t : ""}`;
  }
  if ((m = u.match(/vimeo\.com\/(?:video\/)?(\d+)/i))) return `https://player.vimeo.com/video/${m[1]}`;
  return u;
}

/* ----------------------------------------------------------------------------
   5. ROOM LAYOUT  — generated from the slide count (auto re-layout)
   -------------------------------------------------------------------------- */

/** Build the room for `count` slides: size the grid, place kiosks on a ring,
 *  lay the walkway, and centre the player. @param {number} count */
function buildRoom(count) {
  const n = Math.max(1, count);
  const R = Math.max(3.4, (n * KIOSK_SPACING) / (2 * Math.PI)); // ring radius grows with n
  const margin = 2.5;
  GRID = Math.max(9, Math.ceil(2 * (R + margin)));
  const cx = (GRID - 1) / 2, cy = (GRID - 1) / 2;

  EXHIBITS = [];
  for (let i = 0; i < n; i++) {
    const ang = -Math.PI / 2 + (i * 2 * Math.PI) / n;       // start at top, clockwise
    EXHIBITS.push({
      tx: clamp(Math.round(cx + R * Math.cos(ang)), 1, GRID - 2),
      ty: clamp(Math.round(cy + R * Math.sin(ang)), 1, GRID - 2),
      title: SLIDES[i] ? SLIDES[i].title : `Slide ${i + 1}`,
      color: KIOSK_PALETTE[i % KIOSK_PALETTE.length],
      slide: i,
      visited: false,
    });
  }
  separateExhibits();

  pathTiles.clear();
  for (let i = 0; i < EXHIBITS.length; i++) line(EXHIBITS[i], EXHIBITS[(i + 1) % EXHIBITS.length]);

  player.x = cx; player.y = cy; player.fx = 0; player.fy = 1; player.moving = false;
  activeIndex = prevActive = currentTarget = -1;
  auto.active = false; auto.goal = -1;
}

/** Nudge any kiosks that rounded onto the same tile. */
function separateExhibits() {
  const seen = new Set();
  for (const e of EXHIBITS) {
    let key = e.tx + "," + e.ty, guard = 0;
    while (seen.has(key) && guard++ < 12) {
      e.ty = clamp(e.ty + 1, 1, GRID - 2);
      if (e.ty >= GRID - 2) { e.ty = 1; e.tx = clamp(e.tx + 1, 1, GRID - 2); }
      key = e.tx + "," + e.ty;
    }
    seen.add(key);
  }
}

/** @param {Exhibit} a @param {Exhibit} b — add an L-shaped walkway between two kiosks */
function line(a, b) {
  let x = a.tx, y = a.ty;
  while (x !== b.tx) { pathTiles.add(x + "," + y); x += Math.sign(b.tx - x); }
  while (y !== b.ty) { pathTiles.add(x + "," + y); y += Math.sign(b.ty - y); }
  pathTiles.add(b.tx + "," + b.ty);
}

/* ----------------------------------------------------------------------------
   6. INIT
   -------------------------------------------------------------------------- */

function init() {
  introEl       = must("intro");
  slideEl       = must("slide");
  slideCardEl   = must("slideCard");
  slideTitleEl  = must("slideTitle");
  slideCounterEl= must("slideCounter");
  slideStageEl  = must("slideStage");
  hudHintEl     = must("hudHint");
  hudProgressEl = must("hudProgress");
  startBtn      = /** @type {HTMLButtonElement} */ (must("startBtn"));
  must("introTitle").textContent = TALK_TITLE;
  document.title = TALK_TITLE;

  mpNameWrap = document.getElementById("mpNameWrap");
  mpNameEl   = /** @type {HTMLInputElement|null} */ (document.getElementById("mpName"));
  mpStatusEl = document.getElementById("mpStatus");
  msgComposerEl = document.getElementById("msgComposer");
  msgInputEl    = /** @type {HTMLInputElement|null} */ (document.getElementById("msgInput"));
  if (msgInputEl) msgInputEl.addEventListener("keydown", onComposerKey);
  chatBtnEl = document.getElementById("chatBtn");                         // touch: opens the composer (no F key on a phone)
  if (chatBtnEl) chatBtnEl.addEventListener("click", toggleMessage);
  const msgPostEl = document.getElementById("msgPost"), msgCancelEl = document.getElementById("msgCancel");
  if (msgPostEl) msgPostEl.addEventListener("click", postMessage);        // keyboard-free post / dismiss (no Enter/Esc on mobile)
  if (msgCancelEl) msgCancelEl.addEventListener("click", closeComposer);
  netInit();   // probes for serve.py's relay; no-op (stays single-player) if absent

  sheetIndex = Math.floor(Math.random() * SHEET_THEMES.length); // random ghost
  buildSheetPicker();
  try { buildJoinQR(); } catch (e) { /* a QR hiccup must never block init / the listeners below */ }

  resize();
  window.addEventListener("resize", resize);
  window.addEventListener("keydown", onKeyDown);
  window.addEventListener("keyup", onKeyUp);
  window.addEventListener("blur", () => { keys.up = keys.down = keys.left = keys.right = false; });
  canvas.addEventListener("pointerdown", onCanvasPointer); // tap / click to walk (and tap a kiosk to open it)
  canvas.tabIndex = -1;                 // focusable (out of tab order) so closeSlide() can pull the keyboard back from a slide iframe
  startBtn.addEventListener("click", startGame);
  must("slideClose").addEventListener("click", closeSlide);
  slideEl.addEventListener("click", e => { if (e.target === slideEl) closeSlide(); }); // click backdrop

  // load slides (async because the probe path waits on image loads), then
  // build the room for that many slides and enable Start.
  startBtn.disabled = true; startBtn.textContent = "Loading slides…";
  loadSlides().then(slides => {
    SLIDES = slides;
    buildRoom(SLIDES.length);
    preloadSlideDocs(SLIDES);   // http(s): kiosks then open instantly from srcdoc
    startBtn.disabled = false; startBtn.textContent = "Enter the room →";
  });

  last = performance.now();
  requestAnimationFrame(loop);
}

/** @param {string} id @returns {HTMLElement} */
function must(id) { const el = document.getElementById(id); if (!el) throw new Error("missing #" + id); return el; }

function resize() {
  dpr = Math.min(window.devicePixelRatio || 1, 2);
  W = window.innerWidth; H = window.innerHeight;
  canvas.width = Math.round(W * dpr);
  canvas.height = Math.round(H * dpr);
  canvas.style.width = W + "px"; canvas.style.height = H + "px";
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
}

/** Build the start-screen sheetghost picker from SHEET_THEMES (live, unlabelled
 *  ghost previews — the tooltip carries the accessible name). */
function buildSheetPicker() {
  const wrap = must("sheetPicker");
  wrap.innerHTML = "";
  const d = Math.min(window.devicePixelRatio || 1, 2);
  SHEET_THEMES.forEach((theme, i) => {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "sheet" + (i === sheetIndex ? " sel" : "");
    btn.title = `Sheetghost ${i + 1} of ${SHEET_THEMES.length}`;
    const size = 56;
    const cv = document.createElement("canvas");
    cv.width = size * d; cv.height = size * d;
    cv.style.width = size + "px"; cv.style.height = size + "px";
    const g = /** @type {CanvasRenderingContext2D} */ (cv.getContext("2d"));
    g.setTransform(d, 0, 0, d, 0, 0);
    paintGhost(g, size / 2, size - 8, 1, theme, 0, 0.25);
    btn.appendChild(cv);
    btn.addEventListener("click", () => selectSheet(i));
    wrap.appendChild(btn);
  });
}

/** @param {number} i */
function selectSheet(i) {
  sheetIndex = i;
  audio.ensure(); audio.resume(); sfx.sheet();
  Array.from(must("sheetPicker").children).forEach((el, idx) => el.classList.toggle("sel", idx === sheetIndex));
}

/* --- "Scan to open on your phone" — a QR of this page's own URL on the start
   screen, so an attendee can open the presentation on their phone (and join the
   same room over multiplayer). Drawn with the vendored qrcode-generator (a plain
   <script> include, like tools/qr.html — no build, works offline). Shown only when
   served over http(s) on a routable host; hidden on file:// and loopback, where the
   address wouldn't resolve on a separate device. ------------------------------- */

/** The address to encode in the join QR, or "" when there's nothing shareable. */
function shareableUrl() {
  const j = JOIN_URL.trim();
  if (j) return /^https?:\/\//i.test(j) ? j : "https://" + j;   // explicit override → always shown, points wherever you set it
  if (!/^https?:$/.test(location.protocol)) return "";   // file:// → not reachable from a phone
  const h = location.hostname;
  if (h === "localhost" || h === "127.0.0.1" || h === "0.0.0.0" || h === "::1") return ""; // loopback → only this machine
  return location.origin + location.pathname + location.search; // keep ?room=… ; drop any #hash
}

/** Render the start-screen join QR; no-op (stays hidden) if there's nothing to share. */
function buildJoinQR() {
  const box = document.getElementById("qrJoin");
  const codeEl = document.getElementById("qrCode");
  const urlEl = document.getElementById("qrUrl");
  const make = /** @type {any} */ (window).qrcode;
  const url = shareableUrl();
  if (!box || !codeEl || !urlEl || !url || typeof make !== "function") return;
  const qr = makeQRCode(make, url, "M");
  if (!qr) return;
  codeEl.innerHTML = qrSvg(qr);
  urlEl.textContent = url.replace(/^https?:\/\//, "");
  box.classList.remove("hidden");
}

/** Smallest QR version that fits `text` at error-correction `ecl`. @param {any} make @param {string} text @param {string} ecl */
function makeQRCode(make, text, ecl) {
  try { const a = make(0, ecl); a.addData(text); a.make(); return a; } catch (e) { /* fall through to fixed versions */ }
  for (let t = 1; t <= 40; t++) { try { const m = make(t, ecl); m.addData(text); m.make(); return m; } catch (e2) { /* try the next version */ } }
  return null;
}

/** One crisp <path> over all dark modules, with the spec's 4-module quiet zone. @param {any} qr */
function qrSvg(qr) {
  const QUIET = 4, n = qr.getModuleCount(), total = n + QUIET * 2;
  let path = "";
  for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) if (qr.isDark(r, c)) path += `M${c + QUIET} ${r + QUIET}h1v1h-1z`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" shape-rendering="crispEdges" `
    + `role="img" aria-label="QR code to open this presentation">`
    + `<rect width="${total}" height="${total}" fill="#ffffff"/><path d="${path}" fill="#000000"/></svg>`;
}

/* ----------------------------------------------------------------------------
   7. INPUT
   -------------------------------------------------------------------------- */

/** @param {KeyboardEvent} e */
function onKeyDown(e) {
  const k = e.key.toLowerCase();
  audio.resume();
  if (net.composing) return;            // composing a speech-bubble message — let the text input own the keys

  if (state === "intro") {
    if (!startBtn.disabled && ["enter", " ", "w", "a", "s", "d", "arrowup", "arrowdown", "arrowleft", "arrowright"].includes(k)) {
      e.preventDefault(); startGame();
    }
    return;
  }

  if (state === "slide") {
    // Leave by walking away: any movement key closes the slide and resumes
    // walking — so you never need Esc (which would drop the browser out of
    // fullscreen). E still toggles the slide shut, the same key that opened it.
    if (["w", "a", "s", "d", "arrowup", "arrowdown", "arrowleft", "arrowright"].includes(k)) {
      e.preventDefault();
      closeSlide();
      auto.active = false;                                   // manual movement takes over
      if (k === "w" || k === "arrowup") keys.up = true;      // start walking now; keyup clears it
      else if (k === "s" || k === "arrowdown") keys.down = true;
      else if (k === "a" || k === "arrowleft") keys.left = true;
      else if (k === "d" || k === "arrowright") keys.right = true;
      return;
    }
    if (k === "e" || k === "escape") { e.preventDefault(); closeSlide(); }                // E toggles shut (Esc still works, for non-fullscreen)
    else if (k === " ") { e.preventDefault(); closeSlide(); autoPathNext(); }             // Space → close + auto-walk to next
    else if (k === "," || k === "<") { e.preventDefault(); setSlide(currentSlide - 1); }  // browse: previous slide
    else if (k === "." || k === ">") { e.preventDefault(); setSlide(currentSlide + 1); }  // browse: next slide
    return;
  }

  // walking
  if (["arrowup", "arrowdown", "arrowleft", "arrowright", " "].includes(k)) e.preventDefault();
  if (k === " ") { autoPathNext(); return; }                                       // Space → auto-walk to next
  if (["w", "a", "s", "d", "arrowup", "arrowdown", "arrowleft", "arrowright"].includes(k)) auto.active = false; // manual takes over
  if (k === "w" || k === "arrowup") keys.up = true;
  else if (k === "s" || k === "arrowdown") keys.down = true;
  else if (k === "a" || k === "arrowleft") keys.left = true;
  else if (k === "d" || k === "arrowright") keys.right = true;
  else if (k === "e" || k === "enter") { if (activeIndex >= 0) openSlide(EXHIBITS[activeIndex].slide, activeIndex); }
  else if (k === "c") { sheetIndex = (sheetIndex + 1) % SHEET_THEMES.length; sfx.sheet(); toast(`Sheetghost ${sheetIndex + 1} of ${SHEET_THEMES.length}`); }
  else if (k === "m") { audio.setMuted(!audio.muted); toast(audio.muted ? "Sound off" : "Sound on"); }
  else if (k === "f") { e.preventDefault(); toggleMessage(); }   // post / clear a speech-bubble message (preventDefault so this "f" doesn't leak into the composer it opens)
}

/** @param {KeyboardEvent} e */
function onKeyUp(e) {
  const k = e.key.toLowerCase();
  if (k === "w" || k === "arrowup") keys.up = false;
  else if (k === "s" || k === "arrowdown") keys.down = false;
  else if (k === "a" || k === "arrowleft") keys.left = false;
  else if (k === "d" || k === "arrowright") keys.right = false;
}

/** Tap / click in the play area (touch, pen, or mouse): walk to a tapped kiosk and
 *  open it, otherwise walk to the tapped floor tile. Mirrors the Space auto-walk, so
 *  a phone visitor needs no keyboard. @param {PointerEvent} e */
function onCanvasPointer(e) {
  if (state !== "walking" || net.composing) return;   // only while roaming; ignore taps mid-slide / while typing
  if (e.pointerType === "mouse" && e.button > 0) return; // ignore non-primary MOUSE buttons; always allow touch / pen
  e.preventDefault();
  audio.ensure(); audio.resume();                      // first touch also unlocks audio on mobile
  const r = canvas.getBoundingClientRect();
  const sx = e.clientX - r.left, sy = e.clientY - r.top;
  const ki = kioskAtScreen(sx, sy);
  if (ki >= 0) walkToKiosk(ki);
  else { const w = screenToWorld(sx, sy); walkToPoint(w.x, w.y); }
}

/** Begin auto-walking to a kiosk; it opens once we're in range. @param {number} i exhibit index */
function walkToKiosk(i) {
  auto.active = true; auto.goal = i;
  auto.lastDist = Infinity; auto.stuck = 0;
}

/** Begin auto-walking to a free floor point (tapped tile); we just stop on arrival.
 *  @param {number} tx @param {number} ty */
function walkToPoint(tx, ty) {
  auto.active = true; auto.goal = -1;
  auto.tx = clamp(tx, 0.4, GRID - 1 - 0.4);
  auto.ty = clamp(ty, 0.4, GRID - 1 - 0.4);
  auto.lastDist = Infinity; auto.stuck = 0;
}

/** Auto-walk to (and then open) the next slide; first slide if none reached yet.
 *  This is the hook a future "audio-instruction" navigator would call. */
function autoPathNext() {
  if (!EXHIBITS.length) return;
  let t = currentTarget < 0 ? 0 : currentTarget + 1;
  if (t >= EXHIBITS.length) t = 0;          // wrap around
  walkToKiosk(t);
}

/* --- Speech bubbles (F key) — write a short message that floats over your ghost
   for everyone in the room; press F again to clear it. Drawn as canvas text only
   (never HTML), and length-capped here + on the relay, so a remote message is inert. */

/** F key: open the composer, or — if a message is already up — clear it. */
function toggleMessage() {
  if (net.composing) return;
  if (net.msg) { net.msg = ""; sfx.close(); toast("Message cleared"); return; }
  openComposer();
}

/** Show the little text box and take the keyboard for typing. */
function openComposer() {
  if (!msgComposerEl || !msgInputEl) return;
  net.composing = true;
  msgInputEl.value = "";
  msgComposerEl.classList.remove("hidden");
  msgInputEl.focus();
}

/** Commit what's typed as this ghost's message (sent on the next sync). */
function postMessage() {
  const raw = msgInputEl ? msgInputEl.value : "";
  net.msg = raw.replace(/\s+/g, " ").trim().slice(0, MSG_MAX);
  closeComposer();
  if (net.msg) { sfx.interact(1); toast("Message posted — F or 💬 to clear"); }
}

/** Hide the composer and hand the keyboard back to the game. */
function closeComposer() {
  net.composing = false;
  if (msgComposerEl) msgComposerEl.classList.add("hidden");
  if (msgInputEl) msgInputEl.blur();
  try { canvas.focus(); } catch (_) { /* ignore */ }
}

/** Keys while the composer is focused: Enter posts, Esc cancels; the rest just types.
 *  @param {KeyboardEvent} e */
function onComposerKey(e) {
  e.stopPropagation();                  // keep typing out of the game's movement handler
  if (e.key === "Enter") { e.preventDefault(); postMessage(); }
  else if (e.key === "Escape") { e.preventDefault(); closeComposer(); }
}

function startGame() {
  audio.ensure(); audio.resume();
  sfx.interact(2);
  // future: music.start();  (see GENERATIVE MUSIC note in section 3)
  introEl.classList.add("hidden");
  state = "walking";
  last = performance.now();
}

/* ----------------------------------------------------------------------------
   8. UPDATE
   -------------------------------------------------------------------------- */

/** @param {number} dt seconds */
function update(dt) {
  // desired movement direction: an auto-walk target (a kiosk to open, or a tapped
  // floor point to stop at), else the held keys.
  let dx = 0, dy = 0;
  if (auto.active) {
    const toKiosk = auto.goal >= 0 && auto.goal < EXHIBITS.length;
    const g = toKiosk ? EXHIBITS[auto.goal] : null;
    const gx = (g ? g.tx : auto.tx) - player.x, gy = (g ? g.ty : auto.ty) - player.y;
    const d = Math.hypot(gx, gy);
    const arrive = toKiosk ? INTERACT_RANGE * 0.9 : 0.3;  // 0.3 > max step/frame → no overshoot jitter at a tapped point
    if (d <= arrive) {                                    // arrived
      auto.active = false;
      if (g) { openSlide(g.slide, auto.goal); return; }   // kiosk → modal now open
    } else {
      if (d > auto.lastDist - 1e-3) auto.stuck += dt; else auto.stuck = 0; // blocked (e.g. tapped behind a kiosk)?
      auto.lastDist = d;
      if (auto.stuck > 0.7) auto.active = false;          // give up rather than grind in place
      else { dx = gx; dy = gy; }
    }
  }
  if (!auto.active) {
    if (keys.up)    { dx -= 1; dy -= 1; }
    if (keys.down)  { dx += 1; dy += 1; }
    if (keys.left)  { dx -= 1; dy += 1; }
    if (keys.right) { dx += 1; dy -= 1; }
  }

  player.moving = (dx !== 0 || dy !== 0);
  if (player.moving) {
    const m = Math.hypot(dx, dy);
    dx /= m; dy /= m;
    player.fx = dx; player.fy = dy;
    let nx = player.x + dx * PLAYER_SPEED * dt;
    let ny = player.y + dy * PLAYER_SPEED * dt;

    for (const ex of EXHIBITS) {                          // gentle circular collision
      let ox = nx - ex.tx, oy = ny - ex.ty;
      const d = Math.hypot(ox, oy);
      if (d < OBSTACLE_RADIUS) {
        if (d < 1e-4) { ox = 1; oy = 0; }
        nx = ex.tx + (ox / (d || 1)) * OBSTACLE_RADIUS;
        ny = ex.ty + (oy / (d || 1)) * OBSTACLE_RADIUS;
      }
    }
    const margin = 0.4;
    player.x = clamp(nx, margin, GRID - 1 - margin);
    player.y = clamp(ny, margin, GRID - 1 - margin);
  }

  activeIndex = -1;
  let best = INTERACT_RANGE;
  for (let i = 0; i < EXHIBITS.length; i++) {
    const d = Math.hypot(player.x - EXHIBITS[i].tx, player.y - EXHIBITS[i].ty);
    if (d < best) { best = d; activeIndex = i; }
  }
  if (activeIndex !== prevActive) {
    if (activeIndex >= 0) sfx.enter(activeIndex);
    prevActive = activeIndex;
  }
}

/* ----------------------------------------------------------------------------
   9. RENDER
   -------------------------------------------------------------------------- */

/** @param {number} ts */
function loop(ts) {
  let dt = (ts - last) / 1000;
  if (dt > 0.05) dt = 0.05;
  last = ts; tnow = ts / 1000;
  if (state === "walking") update(dt);
  if (net.on) { netTick(ts); lerpPeers(); }
  render();
  updateHUD();
  requestAnimationFrame(loop);
}

function render() {
  const g = ctx.createLinearGradient(0, 0, 0, H);
  g.addColorStop(0, "#08060f"); g.addColorStop(1, "#0e0a1f");   // dark cyberpunk void — neon lattice floats on it
  ctx.fillStyle = g; ctx.fillRect(0, 0, W, H);

  const ps = isoToScreen(player.x, player.y);
  originX = W / 2 - ps.x;
  originY = H / 2 - ps.y - 24;

  drawFloor();

  /** @type {{depth:number,kind:string,i:number,peer?:Peer}[]} */
  const actors = EXHIBITS.map((e, i) => ({ depth: e.tx + e.ty, kind: "ex", i }));
  actors.push({ depth: player.x + player.y, kind: "pl", i: -1 });
  for (const peer of net.peers.values()) actors.push({ depth: peer.x + peer.y, kind: "peer", i: -1, peer });
  actors.sort((a, b) => a.depth - b.depth);
  for (const a of actors) {
    if (a.kind === "ex") drawExhibit(EXHIBITS[a.i], a.i === activeIndex);
    else if (a.kind === "peer" && a.peer) drawPeer(a.peer);
    else if (a.kind === "pl") drawGhost();
  }

  if (state === "walking" && activeIndex < 0 && !auto.active) drawGuidanceArrow();
  drawToast();
}

function drawFloor() {
  // Cyberpunk lattice: a dark base plane lit by glowing isometric grid lines.
  const lo = -0.5, hi = GRID - 0.5;
  const c00 = toScreen(lo, lo), c10 = toScreen(hi, lo), c11 = toScreen(hi, hi), c01 = toScreen(lo, hi);

  // base plane — slightly deeper than the void so the floor reads as a surface
  poly([[c00.x, c00.y], [c10.x, c10.y], [c11.x, c11.y], [c01.x, c01.y]], "rgba(8,5,20,0.6)");

  // walkway tiles — magenta neon underglow connecting the kiosks
  for (const key of pathTiles) {
    const p = key.split(","); const c = toScreen(+p[0], +p[1]);
    diamond(c.x, c.y, "rgba(255,42,170,0.18)", null);
  }

  // the lattice — every iso grid line batched into one path, stroked twice:
  // a wide cyan bloom then a crisp bright core (save/restore so the glow can't leak)
  ctx.save();
  ctx.lineCap = "round";
  ctx.beginPath();
  for (let a = lo; a <= hi + 1e-6; a += 1) { const s = toScreen(a, lo), e = toScreen(a, hi); ctx.moveTo(s.x, s.y); ctx.lineTo(e.x, e.y); }
  for (let b = lo; b <= hi + 1e-6; b += 1) { const s = toScreen(lo, b), e = toScreen(hi, b); ctx.moveTo(s.x, s.y); ctx.lineTo(e.x, e.y); }
  ctx.shadowColor = "rgba(0,238,255,0.85)"; ctx.shadowBlur = 9;
  ctx.strokeStyle = "rgba(80,247,255,0.50)"; ctx.lineWidth = 1.25; ctx.stroke();   // glow pass
  ctx.shadowBlur = 0;
  ctx.strokeStyle = "rgba(186,253,255,0.92)"; ctx.lineWidth = 0.75; ctx.stroke();  // crisp core
  ctx.restore();

  for (const ex of EXHIBITS) {
    const c = toScreen(ex.tx, ex.ty);
    ctx.save();
    ctx.translate(c.x, c.y); ctx.scale(1, TILE_H / TILE_W);
    const rad = ctx.createRadialGradient(0, 0, 4, 0, 0, TILE_W * 0.62);
    rad.addColorStop(0, hexA(ex.color, 0.5)); rad.addColorStop(1, hexA(ex.color, 0));
    ctx.fillStyle = rad;
    ctx.beginPath(); ctx.arc(0, 0, TILE_W * 0.62, 0, Math.PI * 2); ctx.fill();
    ctx.restore();
  }
}

/** @param {Exhibit} ex @param {boolean} active */
function drawExhibit(ex, active) {
  const c = toScreen(ex.tx, ex.ty);
  const pulse = 0.5 + 0.5 * Math.sin(tnow * 4);

  shadow(c.x, c.y, 34);

  const fw = TILE_W * 0.30, fh = TILE_H * 0.30, ph = 22, topY = c.y - ph;
  poly([[c.x - fw, c.y], [c.x, c.y + fh], [c.x, c.y + fh - ph], [c.x - fw, c.y - ph]], shade(ex.color, -0.45));
  poly([[c.x + fw, c.y], [c.x, c.y + fh], [c.x, c.y + fh - ph], [c.x + fw, c.y - ph]], shade(ex.color, -0.25));
  poly([[c.x, topY - fh], [c.x + fw, topY], [c.x, topY + fh], [c.x - fw, topY]], shade(ex.color, 0.15));

  const sw = 58, sh = 44, sx = c.x - sw / 2, sy = topY - fh - sh - 6;
  roundRect(sx - 3, sy - 3, sw + 6, sh + 6, 8, shade(ex.color, active ? 0.25 : 0.0), null);
  roundRect(sx, sy, sw, sh, 6, "#0d1626", hexA(ex.color, active ? 0.9 : 0.45));
  ctx.fillStyle = hexA(ex.color, active ? 1 : 0.75);
  ctx.font = "800 24px -apple-system,Segoe UI,Roboto,sans-serif";
  ctx.textAlign = "center"; ctx.textBaseline = "middle";
  ctx.fillText(String(ex.slide + 1), c.x, sy + sh / 2 + 1);

  if (ex.visited) {
    ctx.fillStyle = "#1dd1a1";
    ctx.beginPath(); ctx.arc(sx + sw - 2, sy + 2, 9, 0, Math.PI * 2); ctx.fill();
    ctx.fillStyle = "#06121f"; ctx.font = "800 12px sans-serif";
    ctx.fillText("✓", sx + sw - 2, sy + 3);
  }

  label(ex.title, c.x, sy - 12, 15, "#e8eef5");

  if (active) {
    ctx.save();
    ctx.translate(c.x, c.y); ctx.scale(1, TILE_H / TILE_W);
    ctx.strokeStyle = hexA(ex.color, 0.35 + 0.4 * pulse); ctx.lineWidth = 3;
    ctx.beginPath(); ctx.arc(0, 0, TILE_W * (0.5 + 0.08 * pulse), 0, Math.PI * 2); ctx.stroke();
    ctx.restore();

    const py = sy - 34;
    roundRect(c.x - 46, py - 14, 92, 26, 13, hexA(ex.color, 0.95), null);
    ctx.fillStyle = "#06121f"; ctx.font = "700 13px -apple-system,Segoe UI,Roboto,sans-serif";
    ctx.textAlign = "center"; ctx.textBaseline = "middle";
    ctx.fillText("Press  E", c.x, py - 1);
  }
}

/** Draw a sheet-ghost into ANY 2D context. (cx, cyHem) is the hem baseline;
 *  shared by the avatar AND the start-screen picker.
 *  @param {CanvasRenderingContext2D} g @param {number} cx @param {number} cyHem
 *  @param {number} scale @param {SheetTheme} theme @param {number} sdx @param {number} sdy */
function paintGhost(g, cx, cyHem, scale, theme, sdx, sdy) {
  const halfW = 13 * scale, topY = cyHem - 32 * scale, hemY = cyHem;

  g.beginPath();
  g.moveTo(cx - halfW, hemY);
  g.lineTo(cx - halfW, topY);
  g.arc(cx, topY, halfW, Math.PI, Math.PI * 2, false);
  g.lineTo(cx + halfW, hemY);
  const bumps = 4, segW = (halfW * 2) / bumps;
  let x = cx + halfW;
  for (let k = 0; k < bumps; k++) {
    const ex = x - segW, mx = x - segW / 2;
    g.quadraticCurveTo(mx, hemY + 5.5 * scale, ex, hemY);
    x = ex;
  }
  g.closePath();

  const grad = g.createLinearGradient(0, topY - halfW, 0, hemY);
  grad.addColorStop(0, theme.sheet); grad.addColorStop(1, theme.shade);
  g.fillStyle = grad; g.fill();

  if (theme.pattern === "dots") {     // extension point: more cloth patterns
    g.save(); g.clip();
    g.fillStyle = hexA(theme.shade, 0.6);
    const step = 8 * scale;
    for (let yy = topY - halfW; yy < hemY + step; yy += step) {
      const rowOdd = Math.round((yy - (topY - halfW)) / step) % 2;
      for (let xx = cx - halfW; xx <= cx + halfW; xx += step) {
        g.beginPath(); g.arc(xx + rowOdd * step / 2, yy, 1.6 * scale, 0, Math.PI * 2); g.fill();
      }
    }
    g.restore();
  }

  g.lineWidth = 1.5 * scale; g.strokeStyle = "rgba(20,25,45,0.18)"; g.stroke();

  const eyeY = topY - 4 * scale, eyeDX = 5.5 * scale;
  for (const s of [-1, 1]) {
    const exx = cx + s * eyeDX;
    g.fillStyle = "#ffffff";
    g.beginPath(); g.ellipse(exx, eyeY, 4.3 * scale, 5.6 * scale, 0, 0, Math.PI * 2); g.fill();
    g.fillStyle = theme.eye;
    g.beginPath(); g.arc(exx + sdx * 2.2 * scale, eyeY + sdy * 2.4 * scale, 2.3 * scale, 0, Math.PI * 2); g.fill();
  }
}

/** The player avatar: a sheet-ghost that hovers and looks where it walks. */
function drawGhost() {
  const c = toScreen(player.x, player.y);
  const moveBob = player.moving ? Math.sin(tnow * 12) * 1.5 : 0;
  const hover = Math.sin(tnow * 2.2) * 2.2;
  const float = moveBob + hover;

  let sdx = player.fx - player.fy, sdy = (player.fx + player.fy) * 0.5;
  const sm = Math.hypot(sdx, sdy) || 1; sdx /= sm; sdy /= sm;

  shadow(c.x, c.y, 15 - float * 0.4);
  paintGhost(ctx, c.x, c.y - 8 + float, 1, SHEET_THEMES[sheetIndex], sdx, sdy);
  if (net.msg) speechBubble(net.msg, c.x, c.y - 46 + float);     // your own posted message, so you can see what others see
}

/** Chevron near the player pointing toward the nearest unvisited kiosk. */
function drawGuidanceArrow() {
  const n = nextUnvisited();
  if (!n) return;
  const c = toScreen(player.x, player.y), t = toScreen(n.tx, n.ty);
  const a = Math.atan2(t.y - c.y, t.x - c.x);
  const r = 46, x = c.x + Math.cos(a) * r, y = c.y - 60 + Math.sin(a) * r * 0.5;
  ctx.save();
  ctx.translate(x, y); ctx.rotate(a);
  ctx.fillStyle = hexA(n.color, 0.6 + 0.4 * (0.5 + 0.5 * Math.sin(tnow * 5)));
  ctx.beginPath();
  ctx.moveTo(10, 0); ctx.lineTo(-6, -7); ctx.lineTo(-2, 0); ctx.lineTo(-6, 7);
  ctx.closePath(); ctx.fill();
  ctx.restore();
}

function drawToast() {
  if (tnow > toastUntil) return;
  const a = Math.min(1, (toastUntil - tnow) / 0.4);
  ctx.globalAlpha = a;
  ctx.font = "700 14px -apple-system,Segoe UI,Roboto,sans-serif";
  ctx.textAlign = "center"; ctx.textBaseline = "middle";
  const w = ctx.measureText(toastText).width + 30;
  roundRect(W / 2 - w / 2, 18, w, 30, 15, "rgba(13,20,38,0.92)", "rgba(255,255,255,0.12)");
  ctx.fillStyle = "#e8eef5"; ctx.fillText(toastText, W / 2, 34);
  ctx.globalAlpha = 1;
}

function updateHUD() {
  const v = EXHIBITS.filter(e => e.visited).length;
  if (v !== lastVisited) { hudProgressEl.textContent = `Slides viewed: ${v} / ${EXHIBITS.length}`; lastVisited = v; }

  if (mpStatusEl) {
    if (net.on) { mpStatusEl.textContent = `👻 ${net.peers.size + 1} in the room`; mpStatusEl.classList.remove("hidden"); }
    else mpStatusEl.classList.add("hidden");
  }
  // 💬 opener rides along with multiplayer; CSS keeps it hidden unless it's a touch device.
  if (chatBtnEl) chatBtnEl.classList.toggle("show", net.on && state === "walking" && !net.composing);

  let hint;
  if (state !== "walking") hint = lastHint;
  else if (auto.active && auto.goal >= 0) hint = `Walking to “${EXHIBITS[auto.goal].title}”…`;
  else if (auto.active) hint = `On my way…`;
  else if (activeIndex >= 0) hint = `Press E to view “${EXHIBITS[activeIndex].title}”  ·  Space → next`;
  else {
    const n = nextUnvisited();
    hint = n ? `Walk to a kiosk — or press Space to auto-walk to the next slide`
             : `🎉 All slides viewed — Space to revisit from the start`;
  }
  if (hint !== lastHint) { hudHintEl.textContent = hint; lastHint = hint; }
}

/** @returns {Exhibit|null} nearest kiosk not yet visited */
function nextUnvisited() {
  let best = Infinity; /** @type {Exhibit|null} */ let pick = null;
  for (const e of EXHIBITS) {
    if (e.visited) continue;
    const d = Math.hypot(player.x - e.tx, player.y - e.ty);
    if (d < best) { best = d; pick = e; }
  }
  return pick;
}

/* ----------------------------------------------------------------------------
   10. SLIDE MODAL  — image / pdf / html (scrollable) / placeholder
   -------------------------------------------------------------------------- */

/** @param {number} slideIdx @param {number} [exIdx] */
function openSlide(slideIdx, exIdx) {
  currentSlide = clamp(slideIdx, 0, SLIDES.length - 1);
  if (exIdx !== undefined && exIdx >= 0) { EXHIBITS[exIdx].visited = true; currentTarget = exIdx; }
  sfx.interact(exIdx !== undefined && exIdx >= 0 ? exIdx : currentSlide);
  keys.up = keys.down = keys.left = keys.right = false;
  state = "slide";
  renderSlideDOM();
  slideEl.classList.remove("hidden");
  slideCardEl.focus();
}

function closeSlide() {
  sfx.close();
  slideEl.classList.add("hidden");
  slideStageEl.innerHTML = "";          // unload any iframe/PDF
  state = "walking";
  last = performance.now();
  try { canvas.focus(); } catch (_) { /* ignore */ }  // reclaim the keyboard from the slide iframe so movement + keyup reach the game
}

/** @param {number} i */
function setSlide(i) {
  const ni = clamp(i, 0, SLIDES.length - 1);
  if (ni !== currentSlide) sfx.nav();
  currentSlide = ni;
  renderSlideDOM();
}

function renderSlideDOM() {
  const s = SLIDES[currentSlide];
  const type = s.type || (s.html ? "html" : s.src ? guessType(s.src) : "html");
  slideTitleEl.textContent = s.title || `Slide ${currentSlide + 1}`;
  slideCounterEl.textContent = `Slide ${currentSlide + 1} of ${SLIDES.length}`;
  slideStageEl.className = "slide-stage " + type;

  if (type === "image") {
    slideStageEl.innerHTML = `<img class="slide-img" src="${escapeAttr(s.src || "")}" alt="${escapeAttr(s.title)}">`;
  } else if (type === "embed") {
    if (s.src) {
      const url = toEmbedUrl(s.src);
      slideStageEl.innerHTML = `<iframe class="slide-embed" src="${escapeAttr(url)}" title="${escapeAttr(s.title)}"`
        + ` allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share; fullscreen"`
        + ` referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`;
    } else {                            // a pasted <iframe…> embed snippet (presenter-authored)
      slideStageEl.innerHTML = s.html || "";
    }
  } else if (type === "pdf") {
    slideStageEl.innerHTML = `<iframe class="slide-doc" src="${escapeAttr(s.src || "")}#view=FitH" title="${escapeAttr(s.title)}"></iframe>`;
  } else if (s.html) {                // html inline: authored, placeholder, or preloaded (instant)
    slideStageEl.innerHTML = `<iframe class="slide-doc" srcdoc="${escapeAttr(s.html)}" title="${escapeAttr(s.title)}"></iframe>`;
  } else {                            // html from a file (not preloaded — e.g. file://)
    slideStageEl.innerHTML = `<iframe class="slide-doc" src="${escapeAttr(s.src || "")}" title="${escapeAttr(s.title)}"></iframe>`;
  }
  wireSlideIframeKeys();              // let E / Esc / WASD leave the slide even once the iframe owns the keyboard
}

/** A slide iframe (HTML deck, PDF) grabs the keyboard once it's focused — and the
 *  game's keydown listener is on the *parent* window, which iframe key events never
 *  reach. For SAME-ORIGIN iframes we forward just the keys the deck itself doesn't
 *  use — E/Esc (leave) and WASD (walk away) — back to the game; arrows / Space /
 *  PageUp-Down / Home / End / F stay with the deck's own navigator. Cross-origin
 *  iframes (PDF viewer, video embeds) can't be reached, so there the ✕ button leaves. */
function wireSlideIframeKeys() {
  const ifr = /** @type {HTMLIFrameElement|null} */ (slideStageEl.querySelector("iframe"));
  if (!ifr) return;
  ifr.addEventListener("load", () => {
    let doc = null;
    try { doc = ifr.contentDocument; } catch (_) { doc = null; }   // cross-origin → blocked
    if (doc) doc.addEventListener("keydown", onSlideIframeKey);
  });
}

/** Forward a leave/walk-away keypress made *inside* a same-origin slide iframe.
 *  @param {KeyboardEvent} e */
function onSlideIframeKey(e) {
  if (state !== "slide") return;
  const k = (e.key || "").toLowerCase();
  if (k === "e" || k === "escape") { e.preventDefault(); closeSlide(); return; }
  if (k === "w" || k === "a" || k === "s" || k === "d") {        // walk away to leave
    e.preventDefault();
    auto.active = false;
    if (k === "w") keys.up = true;
    else if (k === "s") keys.down = true;
    else if (k === "a") keys.left = true;
    else if (k === "d") keys.right = true;
    closeSlide();                                                // focuses the canvas → the matching keyup reaches the game
  }
  // arrows / Space / PageUp-Down / Home / End / F intentionally left to the deck.
}

function toast(/** @type {string} */ msg) { toastText = msg; toastUntil = tnow + 1.6; }

/** Build the inline-HTML body used by placeholder slides. */
function phCard(/** @type {number} */ n, /** @type {string} */ title, /** @type {string} */ body) {
  return `<!doctype html><meta charset="utf-8"><style>
    html,body{margin:0;height:100%;display:flex;align-items:center;justify-content:center;
      background:radial-gradient(120% 120% at 50% 0%,#1a2742,#101a2e);
      color:#e8eef5;font-family:-apple-system,Segoe UI,Roboto,sans-serif;text-align:center}
    .w{max-width:620px;padding:28px}.n{font-size:64px;font-weight:800;color:#4ecdc4}
    .t{font-size:26px;font-weight:700;margin:10px 0 14px}.b{color:#9fb0c6;font-size:16px;line-height:1.55}
    .note{margin-top:20px;font-size:12px;color:#6f819b}
    code{background:#0d1424;border:1px solid rgba(255,255,255,.1);padding:2px 6px;border-radius:6px}
  </style><div class="w"><div class="n">${n}</div><div class="t">${escapeHtml(title)}</div>
    <p class="b">${escapeHtml(body)}</p>
    <div class="note">Placeholder — add real slides to <code>slides/</code> and run <code>python3 build_slides.py</code>.</div></div>`;
}

/* ----------------------------------------------------------------------------
   11. HELPERS — isometric math, drawing primitives, colour, escaping
   -------------------------------------------------------------------------- */

/** @param {number} wx @param {number} wy */
function isoToScreen(wx, wy) { return { x: (wx - wy) * (TILE_W / 2), y: (wx + wy) * (TILE_H / 2) }; }
/** @param {number} wx @param {number} wy */
function toScreen(wx, wy) { const p = isoToScreen(wx, wy); return { x: p.x + originX, y: p.y + originY }; }

/** Inverse of toScreen: a canvas-relative screen point → world tile coords on the
 *  floor plane (used to turn a tap/click into a walk goal). @param {number} sx @param {number} sy */
function screenToWorld(sx, sy) {
  const ix = sx - originX, iy = sy - originY;          // solve isoToScreen for (wx,wy)
  return { x: ix / TILE_W + iy / TILE_H, y: iy / TILE_H - ix / TILE_W };
}

/** Which kiosk (if any) was tapped: a screen-space hit-box spanning each kiosk's
 *  pillar + sign (taller than its floor tile, so tapping the visible sign counts);
 *  the front-most wins where boxes overlap. @param {number} sx @param {number} sy @returns {number} exhibit index or -1 */
function kioskAtScreen(sx, sy) {
  let pick = -1, bestDepth = -Infinity;
  for (let i = 0; i < EXHIBITS.length; i++) {
    const c = toScreen(EXHIBITS[i].tx, EXHIBITS[i].ty);
    if (sx >= c.x - 34 && sx <= c.x + 34 && sy >= c.y - 96 && sy <= c.y + 18) {
      const depth = EXHIBITS[i].tx + EXHIBITS[i].ty;
      if (depth > bestDepth) { bestDepth = depth; pick = i; }
    }
  }
  return pick;
}

/** @param {number} cx @param {number} cy @param {string} fill @param {string|null} stroke */
function diamond(cx, cy, fill, stroke) {
  ctx.beginPath();
  ctx.moveTo(cx, cy - TILE_H / 2); ctx.lineTo(cx + TILE_W / 2, cy);
  ctx.lineTo(cx, cy + TILE_H / 2); ctx.lineTo(cx - TILE_W / 2, cy);
  ctx.closePath();
  ctx.fillStyle = fill; ctx.fill();
  if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = 1; ctx.stroke(); }
}

/** @param {number[][]} pts @param {string} fill */
function poly(pts, fill) {
  ctx.beginPath(); ctx.moveTo(pts[0][0], pts[0][1]);
  for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i][0], pts[i][1]);
  ctx.closePath(); ctx.fillStyle = fill; ctx.fill();
}

/** @param {number} x @param {number} y @param {number} w @param {number} h @param {number} r @param {string|null} fill @param {string|null} stroke */
function roundRect(x, y, w, h, r, fill, stroke) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r); ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r); ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
  if (fill) { ctx.fillStyle = fill; ctx.fill(); }
  if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = 2; ctx.stroke(); }
}

/** @param {number} cx @param {number} cy @param {number} rx */
function shadow(cx, cy, rx) {
  ctx.save(); ctx.fillStyle = "rgba(0,0,0,0.30)";
  ctx.beginPath(); ctx.ellipse(cx, cy, rx, rx * 0.5, 0, 0, Math.PI * 2); ctx.fill();
  ctx.restore();
}

/** @param {string} text @param {number} x @param {number} y @param {number} size @param {string} color */
function label(text, x, y, size, color) {
  ctx.font = `700 ${size}px -apple-system,Segoe UI,Roboto,sans-serif`;
  ctx.textAlign = "center"; ctx.textBaseline = "alphabetic";
  ctx.lineWidth = 4; ctx.strokeStyle = "rgba(0,0,0,0.6)"; ctx.strokeText(text, x, y);
  ctx.fillStyle = color; ctx.fillText(text, x, y);
}

/** A small speech bubble of `text` whose tail tip sits at (cx, tipY). Canvas text
 *  only — never HTML — so a remote message can't inject markup. Word-wraps to a few
 *  short lines and ellipsises anything that still overflows. @param {string} text */
function speechBubble(text, cx, tipY) {
  const fontSize = 13, lineH = 16, padX = 9, padY = 6, maxTextW = 200, maxLines = 3;
  ctx.font = `600 ${fontSize}px -apple-system,Segoe UI,Roboto,sans-serif`;
  // greedy word-wrap, then clamp to maxLines
  const all = [];
  let line = "";
  for (const w of String(text).split(" ")) {
    const test = line ? line + " " + w : w;
    if (ctx.measureText(test).width > maxTextW && line) { all.push(line); line = w; }
    else line = test;
  }
  if (line) all.push(line);
  const lines = all.slice(0, maxLines);
  if (all.length > maxLines && lines.length) lines[lines.length - 1] += " …";
  for (let i = 0; i < lines.length; i++) {                 // clamp any single over-long line (e.g. one huge word)
    let s = lines[i];
    if (ctx.measureText(s).width > maxTextW) {
      while (s.length > 1 && ctx.measureText(s + "…").width > maxTextW) s = s.slice(0, -1);
      lines[i] = s + "…";
    }
  }
  if (!lines.length) return;
  const tw = Math.min(maxTextW, Math.max.apply(null, lines.map(l => ctx.measureText(l).width)));
  const bw = tw + padX * 2, bh = lines.length * lineH + padY * 2;
  const bx = cx - bw / 2, by = tipY - 7 - bh;             // bubble sits above a 7px tail
  roundRect(bx, by, bw, bh, 9, "rgba(8,12,24,0.92)", "rgba(95,232,255,0.9)");
  ctx.beginPath();                                        // downward tail toward the ghost
  ctx.moveTo(cx - 6, by + bh - 0.5); ctx.lineTo(cx + 6, by + bh - 0.5); ctx.lineTo(cx, by + bh + 7);
  ctx.closePath(); ctx.fillStyle = "rgba(8,12,24,0.92)"; ctx.fill();
  ctx.fillStyle = "#eaf6ff"; ctx.textAlign = "center"; ctx.textBaseline = "middle";
  for (let i = 0; i < lines.length; i++) ctx.fillText(lines[i], cx, by + padY + lineH / 2 + i * lineH);
}

/** Lighten (amt>0) / darken (amt<0) a #rrggbb colour. @param {string} hex @param {number} amt */
function shade(hex, amt) {
  const n = parseInt(hex.slice(1), 16);
  let r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
  const f = amt < 0 ? 0 : 255, p = Math.abs(amt);
  r = Math.round(r + (f - r) * p); g = Math.round(g + (f - g) * p); b = Math.round(b + (f - b) * p);
  return `rgb(${r},${g},${b})`;
}

/** @param {string} hex @param {number} a */
function hexA(hex, a) { const n = parseInt(hex.slice(1), 16); return `rgba(${(n >> 16) & 255},${(n >> 8) & 255},${n & 255},${a})`; }

/** @param {number} v @param {number} lo @param {number} hi */
function clamp(v, lo, hi) { return v < lo ? lo : v > hi ? hi : v; }

/** Escape for element text. @param {string} s */
function escapeHtml(s) { return String(s).replace(/[&<>"]/g, ch => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[ch] || ch)); }
/** Escape for a double-quoted attribute (keeps inner markup intact, e.g. srcdoc). @param {string} s */
function escapeAttr(s) { return String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;"); }

/* --------------------------------------------------------------------------*/
init();
