// AUTO-GENERATED by build_slides.py — do not edit by hand.
// Regenerate after changing the slides/ folder:  python3 build_slides.py
// Each entry: { type: 'image'|'pdf'|'html'|'embed', src: '...', title: '...' }
//   (an html entry may instead use { html: '<inline markup>' } and no src;
//    an embed entry's src is a URL — e.g. a YouTube/Vimeo link — shown 16:9)
window.SLIDES_MANIFEST = [
  {
    "type": "html",
    "src": "slides/placeholder.html",
    "title": "Placeholder"
  }
];
