// AUTO-GENERATED by build_slides.py — do not edit by hand.
// Regenerate after changing the slides/ folder:  python3 build_slides.py
// Each entry: { type: 'image'|'pdf'|'html'|'embed', src: '...', title: '...' }
//   (an html entry may instead use { html: '<inline markup>' } and no src;
//    an embed entry's src is a URL — e.g. a YouTube/Vimeo link — shown 16:9)
window.SLIDES_MANIFEST = [
  {
    "type": "html",
    "src": "slides/01_minimum_viable_soundscapes.html",
    "title": "Minimum Viable Soundscapes"
  },
  {
    "type": "html",
    "src": "slides/02_minimum_viable_product.html",
    "title": "Minimum Viable Product"
  },
  {
    "type": "html",
    "src": "slides/03_the_audio_training_sequence.html",
    "title": "The Audio Training Sequence"
  },
  {
    "type": "html",
    "src": "slides/04_problems_with_the_pipeline.html",
    "title": "Problems With The Pipeline"
  },
  {
    "type": "html",
    "src": "slides/05_a_timeline_of_audio_control.html",
    "title": "A Timeline Of Audio Control"
  },
  {
    "type": "html",
    "src": "slides/06_where_the_timeline_comes_from.html",
    "title": "Where The Timeline Comes From"
  },
  {
    "type": "html",
    "src": "slides/07_the_present_chaosifier.html",
    "title": "The Present Chaosifier"
  },
  {
    "type": "html",
    "src": "slides/08_audio_led_games.html",
    "title": "Audio Led Games"
  },
  {
    "type": "html",
    "src": "slides/09_references_and_links.html",
    "title": "References And Links"
  }
];
