// AUTO-GENERATED by build_slides.py — do not edit by hand.
// Regenerate after changing the slides/ folder:  python3 build_slides.py
// Each entry: { type: 'image'|'pdf'|'html'|'embed', src: '...', title: '...' }
//   (an html entry may instead use { html: '<inline markup>' } and no src;
//    an embed entry's src is a URL — e.g. a YouTube/Vimeo link — shown 16:9)
window.SLIDES_MANIFEST = [
  {
    "type": "html",
    "src": "slides/01_minimum_viable_soundscapes.html",
    "title": "Minimum Viable Soundscapes"
  },
  {
    "type": "html",
    "src": "slides/02_intro.html",
    "title": "Intro"
  },
  {
    "type": "html",
    "src": "slides/03_methods.html",
    "title": "Methods"
  },
  {
    "type": "html",
    "src": "slides/04_descriptive_findings.html",
    "title": "Descriptive Findings"
  },
  {
    "type": "html",
    "src": "slides/05_example_products.html",
    "title": "Example Products"
  },
  {
    "type": "html",
    "src": "slides/06_normative_discussion.html",
    "title": "Normative Discussion"
  },
  {
    "type": "html",
    "src": "slides/07_conceptual_discussion.html",
    "title": "Conceptual Discussion"
  },
  {
    "type": "html",
    "src": "slides/08_additional_references.html",
    "title": "Additional References"
  }
];
